<?php
/**
 * Created by PhpStorm.
 * User: Lukas Figura
 * Date: 30/05/2017
 * Time: 14:40
 */

return [
    'Česko'     => [
        'Juhočeský kraj'        => [
            'České Budějovice',
            'Český Krumlov',
            'Jindřichův Hradec',
            'Písek',
            'Prachatice',
            'Strakonice',
            'Tábor',
        ],
        'Juhomoravský kraj'     => [
            'Blansko',
            'Brno - město',
            'Brno - venkov',
            'Břeclav',
            'Hodonín',
            'Vyškov',
            'Znojmo',
        ],
        'Karlovarský kraj'      => [
            'Cheb',
            'Karlovy Vary',
            'Sokolov',
        ],
        'Královohradecký kraj'  => [
            'Hradec Králové',
            'Jičín',
            'Náchod',
            'Rychnov nad Kněžnou',
            'Trutnov',
        ],
        'Liberecký kraj'        => [
            'Česká Lípa',
            'Jablonec',
            'Liberec',
            'Semily',
        ],
        'Moravskosliezsky kraj' => [
            'Bruntál',
            'Frýdek - Místek',
            'Karviná',
            'Nový Jičín',
            'Opava',
            'Ostrava - město',
        ],
        'Olomoucký kraj'        => [
            'Jeseník',
            'Olomouc',
            'Prostějov',
            'Přerov',
            'Šumperk',
        ],
        'Pardubický kraj'       => [
            'Chrudim',
            'Pardubice',
            'Svitavy',
            'Ústí nad Orlicí',
        ],
        'Plzenský kraj'         => [
            'Domažlice',
            'Klatovy',
            'Plzeň - jih',
            'Plzeň - město',
            'Plzeň - sever',
            'Rokycany',
            'Tachov',
        ],
        'Praha'                 => [
            'Praha'
        ],
        'Stredočeský kraj'      => [
            'Benešov',
            'Beroun',
            'Kladno',
            'Kolín',
            'Kutná Hora',
            'Mělník',
            'Mladá Boleslav',
            'Nymburk',
            'Praha - východ',
            'Praha - západ',
            'Příbram',
            'Rakovník',
        ],
        'Ústecký kraj'          => [
            'Děčín',
            'Chomutov',
            'Litoměřice',
            'Louny',
            'Most',
            'Teplice',
            'Ústí nad Labem',

        ],
        'Kraj Vysočina'         => [
            'Havlíčkův Brod',
            'Jihlava',
            'Pelhřimov',
            'Třebíč',
            'Žďár nad Sázavou',
        ],
        'Zlínsky kraj'          => [
            'Kroměříž',
            'Uherské Hradiště',
            'Vsetín',
            'Zlín',
        ],
    ],
    'Slovensko' => [
        'Banskobystrický kraj' => [
            'Banská Bystrica',
            'Banská Štiavnica',
            'Brezno',
            'Detva',
            'Krupina',
            'Lučenec',
            'Poltár',
            'Revúca',
            'Rimavská Sobota',
            'Veľký Krtíš',
            'Zvolen',
            'Žarnovica',
            'Žiar nad Hronom',
        ],
        'Bratislavský kraj'    => [
            'Bratislava I',
            'Bratislava II',
            'Bratislava III',
            'Bratislava IV',
            'Bratislava V',
            'Malacky',
            'Pezinok',
            'Senec',
        ],
        'Košický kraj'         => [
            'Gelnica',
            'Košice I',
            'Košice II',
            'Košice III',
            'Košice IV',
            'Košice-okolie',
            'Michalovce',
            'Rožňava',
            'Sobrance',
            'Spišská Nová Ves',
            'Trebišov',
        ],
        'Nitriansky kraj'      => [
            'Komárno',
            'Levice',
            'Nitra',
            'Nové Zámky',
            'Šaľa',
            'Topoľčany',
            'Zlaté Moravce',

        ],
        'Prešovský kraj'       => [
            'Bardejov',
            'Humenné',
            'Kežmarok',
            'Levoča',
            'Medzilaborce',
            'Poprad',
            'Prešov',
            'Sabinov',
            'Snina',
            'Stará Ľubovňa',
            'Stropkov',
            'Svidník',
            'Vranov nad Topľou',
        ],
        'Trenčiansky kraj'     => [
            'Bánovce nad Bebravou',
            'Ilava',
            'Myjava',
            'Nové Mesto nad Váhom',
            'Partizánske',
            'Považská Bystrica',
            'Prievidza',
            'Púchov',
            'Trenčín',
        ],
        'Trnavský kraj'        => [
            'Dunajská Streda',
            'Galanta',
            'Hlohovec',
            'Piešťany',
            'Senica',
            'Skalica',
            'Trnava',
        ],
        'Žilinský kraj'        => [
            'Bytča',
            'Čadca',
            'Dolný Kubín',
            'Kysucké Nové Mesto',
            'Liptovský Mikuláš',
            'Martin',
            'Námestovo',
            'Ružomberok',
            'Turčianske Teplice',
            'Tvrdošín',
            'Žilina',
        ],
    ]
];